### ISSUE TITLE
CSS player control icons

### ISSUE THREAD

**Issue by apankow1234** [apankow1234/CaseStudy-Spotify#4]
The `play/pause`, `shuffle`, `repeat`, `next`, and `previous` icons must be as the Spotify icons.

**Comment by apankow1234** [comment]
```css
#main_controls {
	margin: auto;
	min-height: var(--cp-icon-size);
	text-align: center;
}

#main_controls > * {
	visibility: hidden;
	position: relative;
	min-width: calc(100% / 5);
	width: calc(100% / 5);
}
#main_controls > *:after {
	visibility: visible;
	content: "";
	height: var(--cp-icon-size);
	width: var(--cp-icon-size);
	left: 0;
	right: 0;
	bottom: 0;
	margin: auto;
	display: block;
	position: absolute;
	background-size: contain;
	background-position: center center;
	background-repeat: no-repeat;
}
#btn_play_pause:after {
	background-image: var(--img-play);
}
#btn_next:after {
	background-image: var(--img-next);
}
#btn_previous:after {
	background-image: var(--img-previous);
}
#btn_shuffle:after {
	background-image: var(--img-shuffle);
}
#btn_repeat:after {
	background-image: var(--img-repeat);
}
```
