### ISSUE TITLE
Firefox is having difficulties

### ISSUE THREAD

**Issue by apankow1234** [apankow1234/CaseStudy-Spotify#8]
Entire bar is pushed below viewport.

**Comment by apankow1234** [comment]
```css
/*------------------------------------------------------------------------*/
/*            inline and filled out the width of the container            */
/*------------------------------------------------------------------------*/
#control_panel,      /*the whole thing will be laid out horizontally*/
#main_controls,      /*the play/pause/shuffle/etc. buttons should be in a row*/
#play_progress,      /*the timeline and time labels should be in a row*/
#settings,           /*the experience settings should be laid out horizontally*/
#currently_playing,  /*the currently playing art and info should be in a row*/
#media_settings      /*the buttons and timeslider should fill the area... (but vertically)*/
{
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	flex-wrap: wrap;
	align-items: space-between;
}


{
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	/*flex-wrap: wrap;*/
	align-items: space-between;
}
```
